services:
  - type: static
    name: tattoo-rounge-landing
    runtime: node
    plan: free
    buildCommand: bun install && bun run build
    staticPublishPath: ./dist
    envVars:
      - key: NODE_ENV
        value: production
